apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-lew4
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-43256-0011-tenant/ci1t-43256-0011-app/devfile-sample-lew4@sha256:d6ebb2d42716ab4ab33736a8080934ae7704ae3256649aec0e8db35c5b56ef9e
        name: my-nodejs
        resources: {}
status: {}
